---
title: "Tooth Growth"
author: "Alexander Sickert"
date: "23rd September 2015"
output: pdf_document
---


Now in the second portion of the class, we're going to analyze the ToothGrowth data in the R datasets package. 

#Load Data
Load the ToothGrowth data and perform some basic exploratory data analyses 
```{r}
data(ToothGrowth)
str(ToothGrowth)
```


# Summary of Data
Provide a basic summary of the data.

#Tooth Growth by Supplement and Dose

Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering)

#Conclusions and Assumptions

State your conclusions and the assumptions needed for your conclusions. 

Some criteria that you will be evaluated on

    Did you  perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
    Did the student perform some relevant confidence intervals and/or tests?
    Were the results of the tests and/or intervals interpreted in the context of the problem correctly? 
    Did the student describe the assumptions needed for their conclusions?



